name: release

on:
  release:
    types: [created]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the kubectl-watch Docker image
      run: |
        echo $CR_PAT | docker login ghcr.io -u imuxin --password-stdin
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
